"""
Briefing routes – serves the Daily Morning Briefing to the frontend.
Also serves pre-generated workout reviews from the database (auto-generated by scheduler).
"""
import logging
from datetime import date, timedelta
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.database import get_db
from app.dependencies import get_current_user
from app.models import User, MorningBriefing, WorkoutReview, WeightEntry
from app.schemas import BriefingResponse
from app.services.aggregator import gather_user_context
from app.services.ai_service import generate_daily_briefing, generate_session_review, generate_workout_tips, generate_chat_response
from app.services.weather_service import fetch_weather
from app.services.hevy_service import fetch_workout_dates, fetch_recent_workouts
from app.services.yazio_service import fetch_nutrition_dates, fetch_yazio_summary
from app.services.analytics_service import (
    compute_macro_performance_correlation,
    compute_progressive_overload,
    compute_weekly_streaks,
    compute_weekly_report,
    compute_monthly_report,
    compute_achievements,
)
from app.encryption import decrypt_value

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/briefing", tags=["Briefing"])


def _log_weight_entry(user_id, yazio_data: Optional[dict], db: Session):
    """Log today's weight from Yazio data into weight_entries (idempotent)."""
    if not yazio_data or not yazio_data.get("profile"):
        return
    weight = yazio_data["profile"].get("current_weight_kg")
    if not weight or weight <= 0:
        return
    today = date.today()
    existing = (
        db.query(WeightEntry)
        .filter(WeightEntry.user_id == user_id, WeightEntry.date == today)
        .first()
    )
    if existing:
        # Update if weight changed
        if abs(existing.weight_kg - weight) > 0.01:
            existing.weight_kg = weight
            db.commit()
        return
    entry = WeightEntry(user_id=user_id, date=today, weight_kg=round(weight, 2))
    db.add(entry)
    try:
        db.commit()
    except Exception:
        db.rollback()


async def _generate_and_save(
    user: User, db: Session, weather_data: Optional[dict] = None
) -> MorningBriefing:
    """
    Run the full pipeline: gather data → call AI → persist.
    """
    today = date.today()
    lang = user.language or "de"

    # 1) Aggregate Yazio + Hevy data
    context = await gather_user_context(user)

    # Save first_name from Yazio profile if available
    yazio = context.get("yazio")
    if yazio and yazio.get("profile"):
        fn = yazio["profile"].get("first_name", "").strip()
        if fn and fn != (user.first_name or ""):
            user.first_name = fn
            db.commit()
            db.refresh(user)

    # Log weight entry from Yazio
    _log_weight_entry(user.id, yazio, db)

    # Fetch weight history for AI context
    weight_history = (
        db.query(WeightEntry)
        .filter(WeightEntry.user_id == user.id)
        .order_by(WeightEntry.date.desc())
        .limit(90)
        .all()
    )
    weight_history_data = [
        {"date": e.date.isoformat(), "weight_kg": e.weight_kg}
        for e in reversed(weight_history)
    ]

    # 2) Call Gemini
    briefing_data = await generate_daily_briefing(
        yazio_data=context["yazio"],
        hevy_data=context["hevy"],
        weather_data=weather_data,
        language=lang,
        weight_history=weight_history_data,
        today_nutrition=context.get("yazio_today"),
    )

    # 3) Persist
    briefing = MorningBriefing(
        user_id=user.id,
        date=today,
        briefing_data=briefing_data,
    )
    db.add(briefing)
    try:
        db.commit()
        db.refresh(briefing)
    except Exception:
        db.rollback()
        existing = (
            db.query(MorningBriefing)
            .filter(MorningBriefing.user_id == user.id, MorningBriefing.date == today)
            .first()
        )
        if existing:
            return existing
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to save briefing",
        )

    logger.info("Briefing generated for user %s on %s", user.id, today)
    return briefing


@router.get("/today", response_model=BriefingResponse)
async def get_todays_briefing(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
    lat: Optional[float] = Query(None),
    lon: Optional[float] = Query(None),
):
    """
    Return today's morning briefing.
    If one already exists in the DB → return it immediately.
    If not → generate on-demand (optionally with weather), save, and return.
    """
    today = date.today()

    existing = (
        db.query(MorningBriefing)
        .filter(MorningBriefing.user_id == current_user.id, MorningBriefing.date == today)
        .first()
    )
    if existing:
        return existing

    # Fetch weather if location provided
    weather_data = None
    if lat is not None and lon is not None:
        weather_data = await fetch_weather(lat, lon)

    return await _generate_and_save(current_user, db, weather_data)


@router.post("/regenerate", response_model=BriefingResponse)
async def regenerate_briefing(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
    lat: Optional[float] = Query(None),
    lon: Optional[float] = Query(None),
):
    """
    Force-regenerate today's briefing (deletes the old one if present).
    """
    today = date.today()

    db.query(MorningBriefing).filter(
        MorningBriefing.user_id == current_user.id,
        MorningBriefing.date == today,
    ).delete()
    db.commit()

    weather_data = None
    if lat is not None and lon is not None:
        weather_data = await fetch_weather(lat, lon)

    return await _generate_and_save(current_user, db, weather_data)


@router.get("/weather")
async def get_weather(
    lat: float = Query(...),
    lon: float = Query(...),
    current_user: User = Depends(get_current_user),
):
    """
    Return current weather data for the user's location.
    Used by the frontend header for real-time display.
    """
    data = await fetch_weather(lat, lon)
    if not data:
        return {"temperature_c": None, "condition": "Unknown", "emoji": "🌡️"}
    return data


@router.post("/session-review")
async def get_session_review(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Session review — tries to return a pre-generated review from the DB first.
    If none exists, falls back to a live Gemini call (and saves the result).
    Marks the review as read.
    """
    # Try DB first (most recent unread or any recent)
    review = (
        db.query(WorkoutReview)
        .filter(WorkoutReview.user_id == current_user.id)
        .order_by(WorkoutReview.workout_date.desc())
        .first()
    )

    if review and review.review_data:
        # Mark as read
        if not review.is_read:
            review.is_read = True
            db.commit()
        return review.review_data

    # Fallback: generate live (for users who just signed up or have no reviews yet)
    context = await gather_user_context(current_user)

    # Still try to include coaching memory for fallback generation
    previous_review_list = []
    if context.get("hevy") and len(context["hevy"]) > 0:
        latest_workout_name = context["hevy"][0].get("title", "")
        if latest_workout_name:
            prev_reviews = (
                db.query(WorkoutReview)
                .filter(
                    WorkoutReview.user_id == current_user.id,
                    WorkoutReview.workout_name == latest_workout_name,
                )
                .order_by(WorkoutReview.workout_date.desc())
                .limit(3)
                .all()
            )
            previous_review_list = [r.review_data for r in prev_reviews if r.review_data]

    result = await generate_session_review(
        yazio_data=context["yazio"],
        hevy_data=context["hevy"],
        language=current_user.language or "de",
        previous_reviews=previous_review_list,
    )

    return result


@router.get("/workout-reviews")
async def get_workout_reviews(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
    limit: int = Query(20, ge=1, le=50),
):
    """
    Return the user's pre-generated workout reviews from the DB.
    Each item includes the review + tips data, sorted newest first.
    """
    reviews = (
        db.query(WorkoutReview)
        .filter(WorkoutReview.user_id == current_user.id)
        .order_by(WorkoutReview.workout_date.desc())
        .limit(limit)
        .all()
    )

    result = []
    for r in reviews:
        result.append({
            "id": str(r.id),
            "hevy_workout_id": r.hevy_workout_id,
            "workout_name": r.workout_name,
            "workout_date": r.workout_date.isoformat() if r.workout_date else "",
            "is_read": r.is_read,
            "has_review": r.review_data is not None,
            "has_tips": r.tips_data is not None,
            "review_data": r.review_data,
            "tips_data": r.tips_data,
            "created_at": r.created_at.isoformat() if r.created_at else "",
        })

    return result


@router.post("/workout-reviews/{review_id}/read")
async def mark_review_read(
    review_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Mark a specific workout review as read."""
    review = (
        db.query(WorkoutReview)
        .filter(WorkoutReview.id == review_id, WorkoutReview.user_id == current_user.id)
        .first()
    )
    if not review:
        raise HTTPException(status_code=404, detail="Review not found")

    review.is_read = True
    db.commit()
    return {"message": "Marked as read"}


@router.get("/unread-count")
async def get_unread_count(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Return the count of unread workout reviews for badge display."""
    count = (
        db.query(WorkoutReview)
        .filter(
            WorkoutReview.user_id == current_user.id,
            WorkoutReview.is_read == False,
        )
        .count()
    )
    return {"unread_count": count}


@router.post("/trigger-review")
async def trigger_review_check(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Manual trigger — immediately checks for new workouts and generates
    reviews for up to 5 that don't have one yet.
    Already-reviewed workouts are ALWAYS skipped (zero token waste).
    """
    from app.scheduler import _generate_workout_review_for_user

    generated = await _generate_workout_review_for_user(
        current_user, db, max_new_reviews=5
    )
    return {
        "message": f"{generated} new review(s) generated" if generated else "All workouts already reviewed — no tokens used",
        "new_reviews": generated,
    }


@router.get("/workouts")
async def get_workout_list(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Return the user's recent workouts as a lightweight list for the picker.
    No AI involved – just fetches from Hevy.
    """
    context = await gather_user_context(current_user)
    workouts = context.get("hevy") or []

    # Return a simplified list with index, title, date, exercises, duration
    result = []
    for i, w in enumerate(workouts):
        exercise_names = [ex.get("title", "?") for ex in w.get("exercises", [])]
        result.append({
            "index": i,
            "title": w.get("title", "Workout"),
            "date": (w.get("start_time") or "")[:10],
            "duration_min": w.get("duration_min"),
            "exercise_names": exercise_names,
        })

    return result


class WorkoutTipsRequest(BaseModel):
    workout_name: str


@router.post("/workout-tips")
async def get_workout_tips(
    body: WorkoutTipsRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Workout tips — generates forward-looking per-set targets for a workout type.
    Accepts a workout name (from the user's training plan), finds the most recent
    instance in Hevy history, and generates targets with coaching memory.
    """
    context = await gather_user_context(current_user)
    workouts = context.get("hevy") or []

    workout_name = body.workout_name.strip()
    if not workout_name:
        raise HTTPException(status_code=400, detail="Workout name is required")

    # Check if we already have tips in the DB for the most recent instance
    existing = (
        db.query(WorkoutReview)
        .filter(
            WorkoutReview.user_id == current_user.id,
            WorkoutReview.workout_name == workout_name,
        )
        .order_by(WorkoutReview.workout_date.desc())
        .first()
    )
    if existing and existing.tips_data and "exercise_targets" in existing.tips_data:
        # Only use cached tips if they match the new schema (exercise_targets)
        if not existing.is_read:
            existing.is_read = True
            db.commit()
        return existing.tips_data

    # No pre-generated tips (or old schema) — generate live with coaching memory (last 3)
    previous_reviews = (
        db.query(WorkoutReview)
        .filter(
            WorkoutReview.user_id == current_user.id,
            WorkoutReview.workout_name == workout_name,
        )
        .order_by(WorkoutReview.workout_date.desc())
        .limit(3)
        .all()
    )
    previous_tips_list = [r.tips_data for r in previous_reviews if r.tips_data]

    result = await generate_workout_tips(
        yazio_data=context["yazio"],
        hevy_data=workouts,
        workout_name=workout_name,
        language=current_user.language or "de",
        previous_tips_list=previous_tips_list,
    )

    return result


@router.get("/activity-heatmap")
async def get_activity_heatmap(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Return workout dates + nutrition tracking dates for a GitHub-style activity heatmap.
    Returns {workouts: [{date, title, duration_min}], nutrition: [{date, calories, protein}]}.
    """
    workout_dates: list[dict] = []
    nutrition_dates: list[dict] = []

    # Fetch workout dates from Hevy
    if current_user.hevy_api_key:
        try:
            api_key = decrypt_value(current_user.hevy_api_key)
            workout_dates = await fetch_workout_dates(api_key, max_pages=20)
        except Exception as exc:
            logger.error("Failed to fetch workout dates: %s", exc)

    # Fetch nutrition tracking dates from Yazio
    if current_user.yazio_email and current_user.yazio_password:
        try:
            email = decrypt_value(current_user.yazio_email)
            password = decrypt_value(current_user.yazio_password)
            nutrition_dates = await fetch_nutrition_dates(email, password, days=180)
        except Exception as exc:
            logger.error("Failed to fetch nutrition dates: %s", exc)

    return {
        "workouts": workout_dates,
        "nutrition": nutrition_dates,
    }


@router.get("/weight-history")
async def get_weight_history(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
    days: int = Query(90, ge=7, le=365),
):
    """
    Return the user's weight history (last N days).
    Data is collected from Yazio on each briefing generation.
    If no entry for today exists, tries to seed from Yazio on the fly.
    """
    from datetime import timedelta
    today_date = date.today()
    cutoff = today_date - timedelta(days=days)

    # Try to seed today's weight if missing
    today_entry = (
        db.query(WeightEntry)
        .filter(WeightEntry.user_id == current_user.id, WeightEntry.date == today_date)
        .first()
    )
    if not today_entry and current_user.yazio_email and current_user.yazio_password:
        try:
            from app.services.yazio_service import fetch_yazio_summary
            email = decrypt_value(current_user.yazio_email)
            password = decrypt_value(current_user.yazio_password)
            yazio_data = await fetch_yazio_summary(email, password)
            _log_weight_entry(current_user.id, yazio_data, db)
        except Exception as exc:
            logger.debug("Could not seed weight from Yazio: %s", exc)

    entries = (
        db.query(WeightEntry)
        .filter(
            WeightEntry.user_id == current_user.id,
            WeightEntry.date >= cutoff,
        )
        .order_by(WeightEntry.date.asc())
        .all()
    )
    return {
        "entries": [
            {"date": e.date.isoformat(), "weight_kg": round(e.weight_kg, 2)}
            for e in entries
        ],
        "start_weight": entries[0].weight_kg if entries else None,
        "current_weight": entries[-1].weight_kg if entries else None,
        "count": len(entries),
    }


# ════════════════════════════════════════════════════════
#  AI CHAT — conversational coaching
# ════════════════════════════════════════════════════════

class ChatMessage(BaseModel):
    role: str  # "user" or "assistant"
    content: str


class ChatRequest(BaseModel):
    message: str
    conversation_history: list[ChatMessage] = []


@router.post("/chat")
async def coach_chat(
    body: ChatRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Conversational AI Coach chat. The AI knows the user's nutrition, goals,
    training plan (with exercises), and recent workouts. It can answer questions
    about training programming, exercise selection, nutrition, and recovery.
    """
    # Gather full context
    context = await gather_user_context(current_user)

    # Build enriched training plan: map each plan workout name to its exercises
    # by finding the most recent Hevy instance of that workout
    training_plan_enriched: list[dict] | None = None
    plan_names = current_user.training_plan or []
    workouts = context.get("hevy") or []
    if plan_names:
        training_plan_enriched = []
        for plan_name in plan_names:
            exercises: list[str] = []
            # Find the most recent workout matching this plan name
            for w in workouts:
                if w.get("title", "").strip().lower() == plan_name.strip().lower():
                    exercises = [ex.get("title", "?") for ex in w.get("exercises", [])]
                    break
            training_plan_enriched.append({"name": plan_name, "exercises": exercises})

    # Convert conversation history to dicts
    history = [{"role": m.role, "content": m.content} for m in body.conversation_history]

    response_text = await generate_chat_response(
        message=body.message,
        conversation_history=history,
        yazio_data=context["yazio"],
        hevy_data=context["hevy"],
        training_plan_enriched=training_plan_enriched,
        language=current_user.language or "de",
        today_nutrition=context.get("yazio_today"),
        day_before_yesterday_nutrition=context.get("yazio_day_before_yesterday"),
    )

    return {"response": response_text}


# ════════════════════════════════════════════════════════
#  ANALYTICS ENDPOINTS
# ════════════════════════════════════════════════════════

async def _build_nutrition_by_date(user: User, days: int = 180) -> dict:
    """Build a dict of {date_str: {calories, protein, carbs, fat, goals}} from Yazio."""
    if not user.yazio_email or not user.yazio_password:
        return {}

    try:
        email = decrypt_value(user.yazio_email)
        password = decrypt_value(user.yazio_password)
    except Exception:
        return {}

    import asyncio
    import httpx
    from app.services.yazio_service import _yazio_login, YAZIO_BASE_URL, MEAL_KEYS

    nutrition = {}
    today = date.today()

    async with httpx.AsyncClient(timeout=30.0) as client:
        token = await _yazio_login(client, email, password)
        if not token:
            return {}

        semaphore = asyncio.Semaphore(5)

        async def fetch_day(d: date):
            async with semaphore:
                try:
                    resp = await client.get(
                        f"{YAZIO_BASE_URL}/user/widgets/daily-summary",
                        headers={"Authorization": f"Bearer {token}", "Accept": "application/json"},
                        params={"date": d.isoformat()},
                    )
                    if resp.status_code != 200:
                        return
                    data = resp.json()
                    meals = data.get("meals", {})
                    goals = data.get("goals", {})

                    total_cal = 0.0
                    total_prot = 0.0
                    total_carb = 0.0
                    total_fat = 0.0
                    for key in MEAL_KEYS:
                        nutrients = meals.get(key, {}).get("nutrients", {})
                        total_cal += nutrients.get("energy.energy", 0)
                        total_prot += nutrients.get("nutrient.protein", 0)
                        total_carb += nutrients.get("nutrient.carb", 0)
                        total_fat += nutrients.get("nutrient.fat", 0)

                    if total_cal > 0:
                        nutrition[d.isoformat()] = {
                            "calories": round(total_cal, 1),
                            "protein": round(total_prot, 1),
                            "carbs": round(total_carb, 1),
                            "fat": round(total_fat, 1),
                            "goals": {
                                "calories": round(goals.get("energy.energy", 0), 1),
                                "protein": round(goals.get("nutrient.protein", 0), 1),
                                "carbs": round(goals.get("nutrient.carb", 0), 1),
                                "fat": round(goals.get("nutrient.fat", 0), 1),
                            },
                        }
                except Exception:
                    pass

        dates_to_check = [today - timedelta(days=i) for i in range(days)]
        await asyncio.gather(*[fetch_day(d) for d in dates_to_check])

    return nutrition


@router.get("/macro-performance")
async def get_macro_performance(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Macro-Performance Correlation: Links nutrition data with workout performance.
    """
    context = await gather_user_context(current_user, include_today_nutrition=False)
    workouts = context.get("hevy") or []

    # Build nutrition by date (up to 90 days to limit API calls)
    nutrition_by_date = await _build_nutrition_by_date(current_user, days=90)

    result = compute_macro_performance_correlation(workouts, nutrition_by_date)
    return result


@router.get("/progressive-overload")
async def get_progressive_overload(
    current_user: User = Depends(get_current_user),
):
    """
    Progressive Overload Dashboard: Per-exercise progression over time.
    """
    context = await gather_user_context(current_user, include_today_nutrition=False)
    workouts = context.get("hevy") or []
    result = compute_progressive_overload(workouts)
    return result


@router.get("/streaks")
async def get_streaks(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Weekly streaks for training and nutrition."""
    import asyncio

    async def _fetch_workout_dates() -> list[str]:
        if not current_user.hevy_api_key:
            return []
        try:
            api_key = decrypt_value(current_user.hevy_api_key)
            raw = await fetch_workout_dates(api_key, max_pages=10)
            return [w["date"] for w in raw if w.get("date")]
        except Exception as exc:
            logger.error("Failed to fetch workout dates for streaks: %s", exc)
            return []

    async def _fetch_nutrition_dates() -> list[str]:
        if not current_user.yazio_email or not current_user.yazio_password:
            return []
        try:
            email = decrypt_value(current_user.yazio_email)
            password = decrypt_value(current_user.yazio_password)
            raw = await fetch_nutrition_dates(email, password, days=90)
            return [n["date"] for n in raw if n.get("date")]
        except Exception as exc:
            logger.error("Failed to fetch nutrition dates for streaks: %s", exc)
            return []

    workout_dates, nutrition_dates = await asyncio.gather(
        _fetch_workout_dates(),
        _fetch_nutrition_dates(),
    )

    result = compute_weekly_streaks(workout_dates, nutrition_dates)
    return result


@router.get("/weekly-report")
async def get_weekly_report(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
    week_offset: int = Query(0, ge=0, le=52),
):
    """
    Weekly Report with training, nutrition, and weight summary.
    week_offset=0 means current week.
    """
    context = await gather_user_context(current_user, include_today_nutrition=False)
    workouts = context.get("hevy") or []

    # Get nutrition data
    nutrition_by_date = await _build_nutrition_by_date(current_user, days=90)

    # Get weight entries
    weight_entries_raw = (
        db.query(WeightEntry)
        .filter(WeightEntry.user_id == current_user.id)
        .order_by(WeightEntry.date.asc())
        .all()
    )
    weight_entries = [{"date": e.date.isoformat(), "weight_kg": e.weight_kg} for e in weight_entries_raw]

    result = compute_weekly_report(workouts, nutrition_by_date, weight_entries, week_offset)

    # Also compute the previous week for comparison
    prev_result = compute_weekly_report(workouts, nutrition_by_date, weight_entries, week_offset + 1)

    return {
        "current": result,
        "previous": prev_result,
    }


@router.get("/monthly-report")
async def get_monthly_report(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
    month_offset: int = Query(0, ge=0, le=12),
):
    """Monthly Report with comparison to previous month."""
    context = await gather_user_context(current_user, include_today_nutrition=False)
    workouts = context.get("hevy") or []
    nutrition_by_date = await _build_nutrition_by_date(current_user, days=365)

    weight_entries_raw = (
        db.query(WeightEntry)
        .filter(WeightEntry.user_id == current_user.id)
        .order_by(WeightEntry.date.asc())
        .all()
    )
    weight_entries = [{"date": e.date.isoformat(), "weight_kg": e.weight_kg} for e in weight_entries_raw]

    result = compute_monthly_report(workouts, nutrition_by_date, weight_entries, month_offset)
    prev_result = compute_monthly_report(workouts, nutrition_by_date, weight_entries, month_offset + 1)

    return {
        "current": result,
        "previous": prev_result,
    }


@router.get("/achievements")
async def get_achievements(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Compute all achievements/badges for the user."""
    context = await gather_user_context(current_user, include_today_nutrition=False)
    workouts = context.get("hevy") or []

    # Get workout dates
    workout_dates: list[str] = []
    if current_user.hevy_api_key:
        try:
            api_key = decrypt_value(current_user.hevy_api_key)
            raw = await fetch_workout_dates(api_key, max_pages=20)
            workout_dates = [w["date"] for w in raw if w.get("date")]
        except Exception:
            pass

    # Get nutrition dates
    nutrition_dates: list[str] = []
    if current_user.yazio_email and current_user.yazio_password:
        try:
            email = decrypt_value(current_user.yazio_email)
            password = decrypt_value(current_user.yazio_password)
            raw = await fetch_nutrition_dates(email, password, days=365)
            nutrition_dates = [n["date"] for n in raw if n.get("date")]
        except Exception:
            pass

    # Get weight entries
    weight_entries_raw = (
        db.query(WeightEntry)
        .filter(WeightEntry.user_id == current_user.id)
        .order_by(WeightEntry.date.asc())
        .all()
    )
    weight_entries = [{"date": e.date.isoformat(), "weight_kg": e.weight_kg} for e in weight_entries_raw]

    # Get nutrition by date for protein tracking
    nutrition_by_date = await _build_nutrition_by_date(current_user, days=365)

    result = compute_achievements(
        workouts=workouts,
        nutrition_dates=nutrition_dates,
        workout_dates=workout_dates,
        weight_entries=weight_entries,
        nutrition_by_date=nutrition_by_date,
    )
    return result


@router.get("/today-nutrition")
async def get_today_nutrition(
    current_user: User = Depends(get_current_user),
):
    """Get today's live nutrition data from Yazio."""
    if not current_user.yazio_email or not current_user.yazio_password:
        return {"error": "No Yazio credentials"}
    try:
        email = decrypt_value(current_user.yazio_email)
        password = decrypt_value(current_user.yazio_password)
        data = await fetch_yazio_summary(email, password, target_date=date.today())
        if not data:
            return {"error": "Could not fetch today's data"}
        return {
            "totals": data.get("totals", {}),
            "goals": data.get("goals", {}),
            "meals": data.get("meals", {}),
            "food_items": data.get("food_items", {}),
            "water_ml": data.get("water_ml", 0),
        }
    except Exception as exc:
        logger.error("Failed to fetch today's nutrition: %s", exc)
        return {"error": str(exc)}


@router.get("/nutrition-history")
async def get_nutrition_history(
    days: int = 7,
    current_user: User = Depends(get_current_user),
):
    """
    Get nutrition history for the last N days.
    Returns daily totals + goals for charting.
    """
    if not current_user.yazio_email or not current_user.yazio_password:
        return {"error": "No Yazio credentials", "days": []}

    days = min(max(days, 1), 90)  # Clamp 1-90

    try:
        email = decrypt_value(current_user.yazio_email)
        password = decrypt_value(current_user.yazio_password)
    except Exception:
        return {"error": "Decryption failed", "days": []}

    import asyncio
    import httpx
    from app.services.yazio_service import _yazio_login, _fetch_daily_summary, _parse_summary, YAZIO_BASE_URL

    history = []
    today = date.today()

    async with httpx.AsyncClient(timeout=30.0) as client:
        token = await _yazio_login(client, email, password)
        if not token:
            return {"error": "Yazio login failed", "days": []}

        semaphore = asyncio.Semaphore(5)

        async def fetch_day(d: date):
            async with semaphore:
                raw = await _fetch_daily_summary(client, token, d.isoformat())
                if not raw:
                    return None
                parsed = _parse_summary(raw)
                return {
                    "date": d.isoformat(),
                    "totals": parsed.get("totals", {}),
                    "goals": parsed.get("goals", {}),
                }

        dates_to_check = [today - timedelta(days=i) for i in range(days)]
        results = await asyncio.gather(*[fetch_day(d) for d in dates_to_check])

        history = [r for r in results if r is not None]

    # Sort by date ascending
    history.sort(key=lambda x: x["date"])

    return {"days": history}


@router.get("/food-statistics")
async def get_food_statistics(
    days: int = 30,
    current_user: User = Depends(get_current_user),
):
    """
    Get aggregated food statistics for the last N days.
    Returns top foods, top protein sources, top calorie items, top brands, new items this week.
    """
    if not current_user.yazio_email or not current_user.yazio_password:
        return {"error": "No Yazio credentials"}

    days = min(max(days, 7), 90)

    try:
        email = decrypt_value(current_user.yazio_email)
        password = decrypt_value(current_user.yazio_password)
    except Exception:
        return {"error": "Decryption failed"}

    import asyncio
    import httpx
    from collections import Counter, defaultdict
    from app.services.yazio_service import (
        _yazio_login, _fetch_consumed_items, _fetch_product, YAZIO_BASE_URL
    )

    today = date.today()

    async with httpx.AsyncClient(timeout=60.0) as client:
        token = await _yazio_login(client, email, password)
        if not token:
            return {"error": "Yazio login failed"}

        # Fetch consumed items for each day
        semaphore = asyncio.Semaphore(5)
        all_items = []  # List of (date, product_id, amount)

        async def fetch_day(d: date):
            async with semaphore:
                items = await _fetch_consumed_items(client, token, d.isoformat())
                return [(d.isoformat(), item.get("product_id"), item.get("amount", 0))
                        for item in items if item.get("product_id")]

        dates_to_check = [today - timedelta(days=i) for i in range(days)]
        results = await asyncio.gather(*[fetch_day(d) for d in dates_to_check])

        for day_items in results:
            all_items.extend(day_items)

        # Collect unique product IDs
        product_ids = {item[1] for item in all_items}
        product_cache = {}

        async def fetch_with_sem(pid: str):
            async with semaphore:
                await _fetch_product(client, token, pid, product_cache)

        await asyncio.gather(*[fetch_with_sem(pid) for pid in product_ids])

    # Aggregate statistics
    food_frequency = Counter()  # product_id -> count
    food_names = {}  # product_id -> name
    food_brands = {}  # product_id -> brand
    protein_total = defaultdict(float)  # product_id -> total protein
    calorie_total = defaultdict(float)  # product_id -> total calories
    first_seen = {}  # product_id -> first date seen

    for date_str, product_id, amount in all_items:
        food_frequency[product_id] += 1

        product = product_cache.get(product_id)
        if not product:
            continue

        food_names[product_id] = product.get("name", "Unknown")
        food_brands[product_id] = product.get("producer", "")

        nutrients = product.get("nutrients", {})
        protein_total[product_id] += (nutrients.get("nutrient.protein", 0) or 0) * amount
        calorie_total[product_id] += (nutrients.get("energy.energy", 0) or 0) * amount

        if product_id not in first_seen:
            first_seen[product_id] = date_str

    # Top 10 most frequent foods
    top_foods = [
        {"name": food_names.get(pid, "Unknown"), "brand": food_brands.get(pid, ""), "count": count}
        for pid, count in food_frequency.most_common(10)
    ]

    # Top 10 protein sources (by total protein consumed)
    top_protein = sorted(
        [(pid, protein_total[pid]) for pid in protein_total],
        key=lambda x: x[1], reverse=True
    )[:10]
    top_protein_list = [
        {"name": food_names.get(pid, "Unknown"), "brand": food_brands.get(pid, ""), "protein_g": round(total, 1)}
        for pid, total in top_protein
    ]

    # Top 10 calorie bombs (by total calories consumed)
    top_calories = sorted(
        [(pid, calorie_total[pid]) for pid in calorie_total],
        key=lambda x: x[1], reverse=True
    )[:10]
    top_calories_list = [
        {"name": food_names.get(pid, "Unknown"), "brand": food_brands.get(pid, ""), "calories": round(total, 0)}
        for pid, total in top_calories
    ]

    # Top brands
    brand_frequency = Counter(food_brands.get(pid, "") for pid in food_frequency if food_brands.get(pid, ""))
    top_brands = [{"brand": brand, "count": count} for brand, count in brand_frequency.most_common(10)]

    # New this week (first seen in last 7 days)
    week_ago = (today - timedelta(days=7)).isoformat()
    new_this_week = [
        {"name": food_names.get(pid, "Unknown"), "brand": food_brands.get(pid, ""), "first_seen": first_seen[pid]}
        for pid in first_seen
        if first_seen[pid] >= week_ago
    ]

    return {
        "top_foods": top_foods,
        "top_protein": top_protein_list,
        "top_calories": top_calories_list,
        "top_brands": top_brands,
        "new_this_week": new_this_week,
        "days_analyzed": days,
    }


@router.post("/nutrition-analysis")
async def get_nutrition_analysis(
    current_user: User = Depends(get_current_user),
):
    """
    AI-powered nutrition analysis.
    Returns analysis for yesterday, tips for today, and overall patterns.
    """
    from app.services.ai_service import generate_nutrition_analysis

    context = await gather_user_context(current_user)

    response = await generate_nutrition_analysis(
        yazio_yesterday=context.get("yazio"),
        yazio_today=context.get("yazio_today"),
        language=current_user.language or "de",
    )

    return response
